name: GinDemoOne Push Actions Testing 
on: [push]

jobs:
  build:
    runs-on: ubantu-latest
    setps: 
    - name: 'Checkout codes'
      uses: actions/checkout@v3
    - name: Get Git log
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Package Install 
      run: go get . 
    - name: Testing
      run: go test -v ./
    - name: Runing
      run: go run -v ./

